### ISSUE TITLE
Planned features v0.3.0

### ISSUE THREAD

**Issue by robamu** [robamu-org/va108xx-hal-rs#15]
Overview of planned features to have a baseline HAL.

# Licensing & Hosting

- [ ]  Move authorative repository to the external git of the IRS
- [ ] Relicense as Apache-2.0 only according to policy of the IRS

# Library

- [x]  GPIO implementation: #2 and #12
- [x] Basic Timer implementation: #5
- [x] Basic PWM API. PWM is part of Timer peripheral. #23
- [x] Basic SPI implementation: #17 and #18
- [x] Basic I2C implementation: #21
- [x] Basic API for using EDAC functionalities and Utility peripheral: #22

# Examples

- [x] Example using the Cascade features of the TIM peripheral: #25
- [x]  Basic SPI example: #17 and #18
- [x] Basic UART example: #10
- [x] Basic I2C example: Example using REB1 temperature sensor: https://github.com/robamu-org/vorago-reb1-rs/pull/5
